# Base Common Configuration
# This file contains settings shared across all experiments

DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1

LOG:
  TRAIN_PATH: scripts/train_runs/exp
  TEST_PATH: scripts/test_runs/exp

INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  MODEL_PATH: ""

